version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.1
  - dependency-name: hamlit
    versions:
    - 2.14.3
    - 2.14.4
    - 2.14.6
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.2
  - dependency-name: nio4r
    versions:
    - 2.5.4
    - 2.5.5
  - dependency-name: brakeman
    versions:
    - 4.10.1
  - dependency-name: parser
    versions:
    - 3.0.0.0
